// LOCALHOST 

GET http://localhost:8080/users 
### 
GET http://localhost:8080/users/6511bc142324339f4af3c245



### Create user 
POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

 {
    "name": "John Doe",
    "email": "johndoe@email.com",
    "phone": "123-456-7890",
    "address": {
      "street": "123 Main St",
      "city": "Anytown",
      "state": "CA",
      "zipcode": "12345"
    }
 }
### PUT user 
PUT http://localhost:8080/users/652ae2845e56c0abc4102aa0 HTTP/1.1
content-type: application/json

{
  "name": "Jane Smith",
  "email": "jane@email.com",
  "phone": "555-123-4567",
  "address": {
    "street": "456 Elm Street",
    "city": "Springfield",
    "state": "IL",
    "zipcode": "62701"
  },
  "experience":["650bbfdbbb69a69afced80cc"],
  "education": ["650bbfdbbb69a69afced80cd"]  
}

### DELETE user 
DELETE http://localhost:8080/users/652ae2845e56c0abc4102aa0 HTTP/1.1

// PRODUCTION Deploy 
### 
GET https://independent.onrender.com/users 
### 
GET https://independent.onrender.com/users/6511bc142324339f4af3c245 
###
POST https://independent.onrender.com/users HTTP/1.1
content-type: application/json

{
  "name": "Jane Smith",
  "email": "jane@email.com",
  "phone": "555-123-4567",
  "address": {
    "street": "456 Elm Street",
    "city": "Springfield",
    "state": "IL",
    "zipcode": "62701"
  },
  "experience":["650bbfdbbb69a69afced80cc"],
  "education": ["650bbfdbbb69a69afced80cd"]  
}
### PUT user 
PUT https://independent.onrender.com/users/65026abcca4b1c47c1163329 HTTP/1.1
content-type: application/json

{
"firstName":"Valerie", "lastName":"Lockling", "email":"valeri.lockling@gmail.com", "favoriteColor":"Blue", "birthday":"11-10-1997"
} 

### DELETE user 
DELETE https://independent.onrender.com/users/652aeddc2835044cf5d4d3f5 HTTP/1.1




GET http://localhost:8080/likes

###
GET http://localhost:8080/likes/6511bc142324339f4af3c245

###
POST http://localhost:8080/likes HTTP/1.1 
content-type: application/json
{
  "emoji": "like",
  "post": "4332423423fdsf23423",
  "googleUser": "dsf3243242423545235"
}
###
PUT http://localhost:8080/likes/652ae2845e56c0abc4102aa0 HTTP/1.1
content-type: application/json
{
  "emoji": "like",
  "post": "4332423423fdsf23423",
  "googleUser": "dsf3243242423545235"
}
### 
DELETE http://localhost:8080/likes/652ae2845e56c0abc4102aa0 HTTP/1.1

####